name = "InlineStrings"
uuid = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com> and contributors"]
version = "1.4.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Parsers = "2"
julia = "1.6"

[targets]
test = ["Test", "Random", "Serialization"]
